# golangci-lint configuration for TUI Styles
version: 2

linters:
  enable:
    # Core linters (always enabled)
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - unconvert

    # Style and quality linters
    - misspell
    - goconst
    - gocyclo

    # Advanced linters
    - gocritic
    - revive
    - gosec

    # Additional quality checks
    - nolintlint
    - unparam
    - nakedret

  disable:
    # dupl: Disabled because table-driven tests often have similar structure
    - dupl

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  gocritic:
    enabled-checks:
      - appendAssign
      - assignOp
      - boolExprSimplify
      - captLocal
      - commentedOutCode
      - dupImport
      - emptyStringTest
      - indexAlloc
      - nestingReduce
      - nilValReturn
      - rangeValCopy
      - underef
      - unlambda
  revive:
    rules:
      - name: dot-imports
        severity: warning
        disabled: false
      - name: exported
        severity: warning
        disabled: false
      - name: indent-error-flow
        severity: warning
        disabled: false
      - name: var-naming
        severity: warning
        disabled: false
  nakedret:
    max-func-lines: 30

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - testdata

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-rules:
    # Disable dupl for test files (table-driven tests often have similar structure)
    - path: _test\.go
      linters:
        - dupl
